using System;
using System.Collections.Generic;
using System.Text;
using UnityUITransformer.App.Models;
using Figma2Unity.Pipeline;

namespace UnityUITransformer.App.Services
{
    public class UssGenerator
    {
        public string GenerateUss(FigmaNode rootNode)
        {
            if (rootNode == null) throw new ArgumentNullException(nameof(rootNode));

            var sb = new StringBuilder();
            sb.AppendLine("/* Generated by UnityUI Transformer (Pro Max v1.0.0) */");
            sb.AppendLine();

            var visitedClasses = new HashSet<string>();
            TraverseAndGenerateNodeUss(rootNode, sb, visitedClasses);

            return sb.ToString();
        }

        private void TraverseAndGenerateNodeUss(FigmaNode node, StringBuilder sb, HashSet<string> visitedClasses, string? extraMarginRule = null)
        {
            string sanitizedName = UxmlGenerator.SanitizeName(node.Name ?? "Element");
            string className = UxmlGenerator.ToKebabCase(sanitizedName);

            if (!visitedClasses.Contains(className))
            {
                visitedClasses.Add(className);

                var rules = GenerateNodeRules(node, extraMarginRule);
                // Ensure every node with a class receives its CSS block
                sb.AppendLine($".{className} {{");
                if (rules.Count > 0)
                {
                    foreach (var rule in rules)
                    {
                        sb.AppendLine($"    {rule}");
                    }
                }
                else
                {
                    sb.AppendLine("    /* Default layout rules */");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }

            if (node.Children != null && node.Children.Count > 0)
            {
                float spacing = node.ItemSpacing;
                bool hasSpacing = spacing > 0 && !string.IsNullOrEmpty(node.LayoutMode);
                string? modeUpper = node.LayoutMode?.ToUpperInvariant();

                for (int i = 0; i < node.Children.Count; i++)
                {
                    var child = node.Children[i];
                    string? childExtraMargin = null;

                    if (hasSpacing && i < node.Children.Count - 1)
                    {
                        if (modeUpper == "VERTICAL")
                        {
                            childExtraMargin = $"margin-bottom: {spacing:0.##}px;";
                        }
                        else if (modeUpper == "HORIZONTAL")
                        {
                            childExtraMargin = $"margin-right: {spacing:0.##}px;";
                        }
                    }

                    TraverseAndGenerateNodeUss(child, sb, visitedClasses, childExtraMargin);
                }
            }
        }

        public List<string> GenerateNodeRules(FigmaNode node, string? extraMarginRule = null)
        {
            var rules = new List<string>();
            bool isTextNode = string.Equals(node.Type, "TEXT", StringComparison.OrdinalIgnoreCase);

            // 1. Layout & Dimensions (Responsive Flexbox via UssStyleBuilder)
            UssStyleBuilder.AppendLayoutRule(node, rules);

            // 2. Fills (Background Color for Containers / Text Color for Labels)
            if (node.Fills != null && node.Fills.Count > 0)
            {
                var visibleFill = node.Fills.Find(f => f.Visible != false && f.Color != null);
                if (visibleFill?.Color != null)
                {
                    string rgba = visibleFill.Color.ToRgbaString(visibleFill.Opacity ?? 1f);
                    if (isTextNode)
                    {
                        rules.Add($"color: {rgba};");
                    }
                    else
                    {
                        rules.Add($"background-color: {rgba};");
                    }
                }
            }

            // 3. Typography & Text Styles (TextMeshPro Font Definition Mapping)
            UssStyleBuilder.AppendTypographyRule(node, rules);

            if (node.Style != null)
            {
                if (node.Style.FontWeight.HasValue && node.Style.FontWeight.Value >= 600)
                {
                    rules.Add("-unity-font-style: bold;");
                }

                if (!string.IsNullOrEmpty(node.Style.TextAlignHorizontal))
                {
                    string align = node.Style.TextAlignHorizontal.ToUpperInvariant();
                    switch (align)
                    {
                        case "LEFT": rules.Add("-unity-text-align: middle-left;"); break;
                        case "CENTER": rules.Add("-unity-text-align: middle-center;"); break;
                        case "RIGHT": rules.Add("-unity-text-align: middle-right;"); break;
                    }
                }
            }

            // 4. Strokes & Borders
            if (node.Strokes != null && node.Strokes.Count > 0)
            {
                var visibleStroke = node.Strokes.Find(s => s.Visible != false && s.Color != null);
                if (visibleStroke?.Color != null)
                {
                    rules.Add($"border-color: {visibleStroke.Color.ToRgbaString(visibleStroke.Opacity ?? 1f)};");
                    float weight = node.StrokeWeight ?? 1f;
                    rules.Add($"border-width: {weight:0.##}px;");
                }
            }

            // 5. Corner Radius
            if (node.CornerRadius.HasValue && node.CornerRadius.Value > 0)
            {
                rules.Add($"border-radius: {node.CornerRadius.Value:0.##}px;");
            }

            // 6. Flexbox Layout Mode & Alignment
            if (!string.IsNullOrEmpty(node.LayoutMode))
            {
                string mode = node.LayoutMode.ToUpperInvariant();
                if (mode == "HORIZONTAL")
                {
                    rules.Add("flex-direction: row;");
                }
                else if (mode == "VERTICAL")
                {
                    rules.Add("flex-direction: column;");
                }

                // Primary Axis (justify-content)
                if (!string.IsNullOrEmpty(node.PrimaryAxisAlignItems))
                {
                    string primary = node.PrimaryAxisAlignItems.ToUpperInvariant();
                    switch (primary)
                    {
                        case "MIN": rules.Add("justify-content: flex-start;"); break;
                        case "CENTER": rules.Add("justify-content: center;"); break;
                        case "MAX": rules.Add("justify-content: flex-end;"); break;
                        case "SPACE_BETWEEN": rules.Add("justify-content: space-between;"); break;
                    }
                }

                // Counter Axis (align-items)
                if (!string.IsNullOrEmpty(node.CounterAxisAlignItems))
                {
                    string counter = node.CounterAxisAlignItems.ToUpperInvariant();
                    switch (counter)
                    {
                        case "MIN": rules.Add("align-items: flex-start;"); break;
                        case "CENTER": rules.Add("align-items: center;"); break;
                        case "MAX": rules.Add("align-items: flex-end;"); break;
                    }
                }
            }

            // 7. Item Spacing / Gap Polyfill (Applied via sibling extraMarginRule)
            if (!string.IsNullOrEmpty(extraMarginRule))
            {
                rules.Add(extraMarginRule);
            }

            // 8. Padding
            if (node.PaddingLeft > 0)
                rules.Add($"padding-left: {node.PaddingLeft:0.##}px;");
            if (node.PaddingRight > 0)
                rules.Add($"padding-right: {node.PaddingRight:0.##}px;");
            if (node.PaddingTop > 0)
                rules.Add($"padding-top: {node.PaddingTop:0.##}px;");
            if (node.PaddingBottom > 0)
                rules.Add($"padding-bottom: {node.PaddingBottom:0.##}px;");

            // 9. Background Image Mapping
            bool hasImageFill = node.Fills != null && node.Fills.Exists(f => 
                f.Visible != false && 
                (!string.IsNullOrEmpty(f.ImageRef) || string.Equals(f.Type, "IMAGE", StringComparison.OrdinalIgnoreCase)));

            bool isImageOrVector = string.Equals(node.Type, "IMAGE", StringComparison.OrdinalIgnoreCase) ||
                                   string.Equals(node.Type, "VECTOR", StringComparison.OrdinalIgnoreCase);

            if (hasImageFill || isImageOrVector)
            {
                string safeName = UxmlGenerator.SanitizeName(node.Name ?? "Image");
                rules.Add($"background-image: url('project://database/Assets/Figma2Unity/Images/{safeName}.png');");
            }

            return rules;
        }
    }
}
