using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEngine;
using Figma2Unity.Editor.Schema;

namespace Figma2Unity.Editor.Generator
{
    public static class USSStyleGenerator
    {
        public static string GenerateUSS(IRDocument document, string packageName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("/* Automatically generated by Figma2Unity Importer */");
            sb.AppendLine();

            // 1. Output :root custom properties block for design tokens
            if (document?.tokens != null)
            {
                bool hasTokens = false;
                var rootTokensSb = new StringBuilder();
                rootTokensSb.AppendLine(":root {");

                if (document.tokens.colors != null && document.tokens.colors.Count > 0)
                {
                    foreach (var cToken in document.tokens.colors)
                    {
                        if (cToken.value != null)
                        {
                            hasTokens = true;
                            string varName = UIToolkitGenerator.SanitizeTokenVarName(cToken.name ?? cToken.id);
                            int r = UIToolkitGenerator.ConvertColorChannel(cToken.value.r);
                            int g = UIToolkitGenerator.ConvertColorChannel(cToken.value.g);
                            int b = UIToolkitGenerator.ConvertColorChannel(cToken.value.b);
                            rootTokensSb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    --color-{0}: rgba({1}, {2}, {3}, {4:F2});", varName, r, g, b, cToken.value.a));
                        }
                    }
                }

                if (document.tokens.spacing != null && document.tokens.spacing.Count > 0)
                {
                    foreach (var sToken in document.tokens.spacing)
                    {
                        hasTokens = true;
                        string varName = UIToolkitGenerator.SanitizeTokenVarName(sToken.name ?? sToken.id);
                        rootTokensSb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    --spacing-{0}: {1}px;", varName, sToken.value));
                    }
                }

                if (document.tokens.typography != null && document.tokens.typography.Count > 0)
                {
                    foreach (var tToken in document.tokens.typography)
                    {
                        if (tToken.fontSize > 0)
                        {
                            hasTokens = true;
                            string varName = UIToolkitGenerator.SanitizeTokenVarName(tToken.name ?? tToken.id);
                            rootTokensSb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    --font-size-{0}: {1}px;", varName, tToken.fontSize));
                        }
                    }
                }

                rootTokensSb.AppendLine("}");

                if (hasTokens)
                {
                    sb.Append(rootTokensSb.ToString());
                    sb.AppendLine();
                }
            }

            var generatedClasses = new HashSet<string>();

            if (document?.rootNodes != null)
            {
                foreach (var rootNode in document.rootNodes)
                {
                    // Pass true for isRoot on top-level frames, "NONE" for parentLayoutMode
                    GenerateNodeStylesRecursive(rootNode, sb, generatedClasses, document, true, "NONE", packageName);
                }
            }

            return sb.ToString();
        }

        public static void GenerateNodeStylesRecursive(
            IRNode node,
            StringBuilder sb,
            HashSet<string> generatedClasses,
            IRDocument document,
            bool isRoot,
            string parentLayoutMode,
            string packageName)
        {
            if (node == null) return;

            string className = SanitizeClassName(node.name, node.id);
            if (!generatedClasses.Contains(className))
            {
                generatedClasses.Add(className);
                sb.AppendLine($".{className} {{");

                // Route all layout positioning, sizing, flexbox, gap, and padding through UnifiedLayoutResolver
                var layoutResult = UnifiedLayoutResolver.ResolveLayoutConstraints(node, isRoot, parentLayoutMode);
                foreach (var rule in layoutResult.Rules)
                {
                    sb.AppendLine($"    {rule}");
                }

                // 2. IMAGE & VECTOR ASSET LINKING
                string pkg = string.IsNullOrEmpty(packageName) ? "SyncPackage" : packageName;

                bool isVectorOrIcon = (node.type != null && string.Equals(node.type, "VECTOR", StringComparison.OrdinalIgnoreCase)) ||
                                      (node.name != null && node.name.IndexOf("icon", StringComparison.OrdinalIgnoreCase) >= 0) ||
                                      node is VectorNode;

                // Target the Nested Opacity & Handle Multi-Fills
                Fill imageFill = node.fills?.Find(f => string.Equals(f.type, "IMAGE", StringComparison.OrdinalIgnoreCase));
                bool hasImageFill = imageFill != null;
                string imageRef = (node as ImageNode)?.imageAssetRef;
                if (string.IsNullOrEmpty(imageRef) && node is VectorNode vecNode)
                {
                    imageRef = vecNode.svgAssetRef;
                }
                bool isFrameWithImage = false;
                
                // FrameNodes with IMAGE fills use the Stack Method (dedicated background layer)
                if (string.IsNullOrEmpty(imageRef) && node is FrameNode frameNodeImg)
                {
                    imageRef = frameNodeImg.imageAssetRef;
                    if (string.IsNullOrEmpty(imageRef) && hasImageFill)
                    {
                        string sanitizedId = node.id.Replace(":", "_").Replace("/", "_");
                        imageRef = $"images/{sanitizedId}_1x.png";
                    }
                    if (!string.IsNullOrEmpty(imageRef))
                    {
                        isFrameWithImage = true;
                    }
                }

                // If node is a vector/icon node and imageRef is still null/empty, route through image pipeline
                if (string.IsNullOrEmpty(imageRef) && isVectorOrIcon)
                {
                    string sanitizedId = node.id.Replace(":", "_").Replace("/", "_");
                    imageRef = $"images/{sanitizedId}_1x.png";
                }

                // Apply background-image directly to element ONLY if it's NOT a FrameNode background image layer
                if (!isFrameWithImage)
                {
                    if (!string.IsNullOrEmpty(imageRef))
                    {
                        string cleanAssetRef = UIToolkitGenerator.SanitizeAssetPath(imageRef);
                        string relAssetPath = $"Assets/Figma2UnityImports/{pkg}/{cleanAssetRef}".Replace('\\', '/');
                        string targetUrl = $"project://database/{relAssetPath}";
                        
                        sb.AppendLine($"    background-image: url('{targetUrl}');");
                        if (isVectorOrIcon)
                        {
                            sb.AppendLine("    -unity-background-scale-mode: scale-to-fit;");
                        }
                        else
                        {
                            sb.AppendLine("    -unity-background-scale-mode: stretch-to-fill;");
                        }

                        float dynamicAlpha = 1.0f;
                        if (imageFill != null && imageFill.opacity.HasValue) {
                            dynamicAlpha = imageFill.opacity.Value;
                        } 
                        else if (imageFill != null && imageFill.color != null && imageFill.color.a < 1.0f) {
                            dynamicAlpha = imageFill.color.a;
                        } 
                        else if (node.opacity < 1.0f) {
                            dynamicAlpha = node.opacity;
                        }

                        if (dynamicAlpha < 1.0f) {
                            sb.AppendLine(string.Format(CultureInfo.InvariantCulture, 
                                "    -unity-background-image-tint-color: rgba(255, 255, 255, {0:F2});", dynamicAlpha));
                        }
                    }
                }

                // 2.5 FILLS & EXPLICIT TRANSPARENCY BY DEFAULT
                bool hasSolidBgFill = false;
                if (node.fills != null && node.fills.Count > 0)
                {
                    foreach (var fill in node.fills)
                    {
                        if (fill.type != "SOLID") continue;

                        ColorValue colorVal = fill.color;
                        string matchedTokenVar = null;

                        if (!string.IsNullOrEmpty(fill.tokenId) && document?.tokens?.colors != null)
                        {
                            var token = document.tokens.colors.Find(t => t.id == fill.tokenId);
                            if (token != null)
                            {
                                colorVal = token.value;
                                matchedTokenVar = $"var(--color-{UIToolkitGenerator.SanitizeTokenVarName(token.name ?? token.id)})";
                            }
                        }

                        if (matchedTokenVar == null && colorVal != null && document?.tokens?.colors != null)
                        {
                            var token = document.tokens.colors.Find(t => t.value != null &&
                                Math.Abs(t.value.r - colorVal.r) < 0.01f &&
                                Math.Abs(t.value.g - colorVal.g) < 0.01f &&
                                Math.Abs(t.value.b - colorVal.b) < 0.01f &&
                                Math.Abs(t.value.a - colorVal.a) < 0.01f);
                            if (token != null)
                            {
                                matchedTokenVar = $"var(--color-{UIToolkitGenerator.SanitizeTokenVarName(token.name ?? token.id)})";
                            }
                        }

                        if (matchedTokenVar != null || colorVal != null)
                        {
                            float alpha = fill.opacity.HasValue ? fill.opacity.Value : (colorVal?.a ?? 1f);
                            if (alpha > 0f)
                            {
                                string colorValueStr;
                                if (matchedTokenVar != null)
                                {
                                    colorValueStr = matchedTokenVar;
                                }
                                else
                                {
                                    int r = UIToolkitGenerator.ConvertColorChannel(colorVal.r);
                                    int g = UIToolkitGenerator.ConvertColorChannel(colorVal.g);
                                    int b = UIToolkitGenerator.ConvertColorChannel(colorVal.b);
                                    colorValueStr = string.Format(CultureInfo.InvariantCulture, "rgba({0}, {1}, {2}, {3:F2})", r, g, b, alpha);
                                }

                                if (node is TextNode)
                                {
                                    sb.AppendLine($"    color: {colorValueStr};");
                                }
                                else if (!isVectorOrIcon)
                                {
                                    sb.AppendLine($"    background-color: {colorValueStr};");
                                    hasSolidBgFill = true;
                                }
                                break;
                            }
                        }
                    }
                }

                // Explicit Transparency by Default for non-text elements without solid fills
                if (!hasSolidBgFill && !(node is TextNode))
                {
                    sb.AppendLine("    background-color: transparent;");
                }

                // 3. FORCE BORDER RADIUS FOR ELLIPSE & OTHER SHAPES
                if (node is EllipseNode)
                {
                    sb.AppendLine("    border-radius: 50%;");
                }
                else if (node.cornerRadius != null)
                {
                    var r = node.cornerRadius;
                    if (r.topLeft > 0 || r.topRight > 0 || r.bottomRight > 0 || r.bottomLeft > 0)
                    {
                        if (r.topLeft == r.topRight && r.topRight == r.bottomRight && r.bottomRight == r.bottomLeft)
                        {
                            sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-radius: {0}px;", r.topLeft));
                        }
                        else
                        {
                            if (r.topLeft > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-top-left-radius: {0}px;", r.topLeft));
                            if (r.topRight > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-top-right-radius: {0}px;", r.topRight));
                            if (r.bottomRight > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-bottom-right-radius: {0}px;", r.bottomRight));
                            if (r.bottomLeft > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-bottom-left-radius: {0}px;", r.bottomLeft));
                        }
                    }
                }

                // 4. STROKES (BORDER)
                if (node.strokes != null && node.strokes.Count > 0)
                {
                    var stroke = node.strokes[0];
                    if (stroke.weight > 0)
                    {
                        sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-width: {0}px;", stroke.weight));
                        ColorValue strokeColor = stroke.color;
                        string matchedStrokeTokenVar = null;

                        if (!string.IsNullOrEmpty(stroke.tokenId) && document?.tokens?.colors != null)
                        {
                            var token = document.tokens.colors.Find(t => t.id == stroke.tokenId);
                            if (token != null)
                            {
                                strokeColor = token.value;
                                matchedStrokeTokenVar = $"var(--color-{UIToolkitGenerator.SanitizeTokenVarName(token.name ?? token.id)})";
                            }
                        }

                        if (matchedStrokeTokenVar != null)
                        {
                            sb.AppendLine($"    border-color: {matchedStrokeTokenVar};");
                        }
                        else if (strokeColor != null)
                        {
                            int r = UIToolkitGenerator.ConvertColorChannel(strokeColor.r);
                            int g = UIToolkitGenerator.ConvertColorChannel(strokeColor.g);
                            int b = UIToolkitGenerator.ConvertColorChannel(strokeColor.b);
                            sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-color: rgba({0}, {1}, {2}, {3:F2});", r, g, b, strokeColor.a));
                        }
                    }
                }

                // 5. OPACITY
                if (node.opacity < 1.0f && !isFrameWithImage)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    opacity: {0:F2};", node.opacity));
                }

                // 6. TYPOGRAPHY & TEXT WRAPPING FOR TEXT NODES
                if (node is TextNode textNode)
                {
                    sb.AppendLine("    white-space: normal;");

                    float? fontSize = textNode.fontSize;
                    string matchedFontSizeVar = null;

                    if (!string.IsNullOrEmpty(textNode.typographyTokenId) && document?.tokens?.typography != null)
                    {
                        var topoToken = document.tokens.typography.Find(t => t.id == textNode.typographyTokenId);
                        if (topoToken != null && topoToken.fontSize > 0)
                        {
                            fontSize = topoToken.fontSize;
                            matchedFontSizeVar = $"var(--font-size-{UIToolkitGenerator.SanitizeTokenVarName(topoToken.name ?? topoToken.id)})";
                        }
                    }

                    if (matchedFontSizeVar != null)
                    {
                        sb.AppendLine($"    font-size: {matchedFontSizeVar};");
                    }
                    else if (fontSize.HasValue && fontSize.Value > 0)
                    {
                        sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    font-size: {0}px;", fontSize.Value));
                    }

                    if (!string.IsNullOrEmpty(textNode.fontFamily))
                    {
                        string fontUrl = UIToolkitGenerator.ResolveFontDefinitionUrl(textNode);
                        if (!string.IsNullOrEmpty(fontUrl))
                        {
                            sb.AppendLine($"    -unity-font-definition: url('{fontUrl}');");
                        }
                    }

                    if (textNode.fontWeight.HasValue && textNode.fontWeight.Value >= 600)
                    {
                        sb.AppendLine("    -unity-font-style: bold;");
                    }

                    string unityTextAlign = UIToolkitGenerator.TranslateUnityTextAlign(textNode.textAlign, textNode.textAlignVertical);
                    sb.AppendLine($"    -unity-text-align: {unityTextAlign};");

                    if (string.Equals(textNode.textDecoration, "UNDERLINE", StringComparison.OrdinalIgnoreCase))
                    {
                        sb.AppendLine("    border-bottom-width: 1px;");
                        sb.AppendLine("    border-bottom-color: initial;");
                    }
                }

                // 7. SAFE BORDER OVERRIDE (CSS Cascade)
                if (node.type == "IMAGE" || node.type == "VECTOR" || (node.name != null && node.name.StartsWith("icon")))
                {
                    sb.AppendLine("    border-width: 0px;");
                    sb.AppendLine("    border-color: transparent;");
                }

                sb.AppendLine("}");
                sb.AppendLine();

                // 8. DEDICATED BACKGROUND IMAGE STACK LAYER FOR FRAMES
                if (isFrameWithImage && !string.IsNullOrEmpty(imageRef))
                {
                    string cleanAssetRef = UIToolkitGenerator.SanitizeAssetPath(imageRef);
                    string relAssetPath = $"Assets/Figma2UnityImports/{pkg}/{cleanAssetRef}".Replace('\\', '/');
                    string targetUrl = $"project://database/{relAssetPath}";

                    float dynamicAlpha = 1.0f;
                    if (imageFill != null && imageFill.opacity.HasValue) {
                        dynamicAlpha = imageFill.opacity.Value;
                    } 
                    else if (imageFill != null && imageFill.color != null && imageFill.color.a < 1.0f) {
                        dynamicAlpha = imageFill.color.a;
                    } 
                    else if (node.opacity < 1.0f) {
                        dynamicAlpha = node.opacity;
                    }

                    sb.AppendLine($".{className}-bg-image {{");
                    sb.AppendLine("    position: absolute;");
                    sb.AppendLine("    top: 0;");
                    sb.AppendLine("    left: 0;");
                    sb.AppendLine("    right: 0;");
                    sb.AppendLine("    bottom: 0;");
                    sb.AppendLine($"    background-image: url('{targetUrl}');");
                    sb.AppendLine("    -unity-background-scale-mode: stretch-to-fill;");
                    sb.AppendLine("    background-color: transparent;");

                    if (dynamicAlpha < 1.0f) {
                        sb.AppendLine(string.Format(CultureInfo.InvariantCulture, 
                            "    -unity-background-image-tint-color: rgba(255, 255, 255, {0:F2});", dynamicAlpha));
                    }

                    sb.AppendLine("}");
                    sb.AppendLine();
                }
            }

            // Recurse children
            if (node is ComponentInstanceNode compNodeCheck)
            {
                bool isBtn = (compNodeCheck.componentName != null && compNodeCheck.componentName.IndexOf("Button", StringComparison.OrdinalIgnoreCase) >= 0) ||
                             (compNodeCheck.name != null && compNodeCheck.name.IndexOf("Button", StringComparison.OrdinalIgnoreCase) >= 0);
                if (isBtn)
                {
                    return;
                }
            }

            string currentLayoutMode = (node.autoLayout != null && !string.IsNullOrEmpty(node.autoLayout.layoutMode)) ? node.autoLayout.layoutMode : "NONE";

            if (node is FrameNode frameNode && frameNode.children != null)
            {
                foreach (var child in frameNode.children)
                {
                    GenerateNodeStylesRecursive(child, sb, generatedClasses, document, false, currentLayoutMode, packageName);
                }
            }
            else if (node is GroupNode groupNode && groupNode.children != null)
            {
                foreach (var child in groupNode.children)
                {
                    GenerateNodeStylesRecursive(child, sb, generatedClasses, document, false, currentLayoutMode, packageName);
                }
            }
            else if (node is ComponentInstanceNode genericCompNode && genericCompNode.children != null)
            {
                foreach (var child in genericCompNode.children)
                {
                    GenerateNodeStylesRecursive(child, sb, generatedClasses, document, false, currentLayoutMode, packageName);
                }
            }
            else if (node is UnsupportedNode unsupNode && unsupNode.children != null)
            {
                foreach (var child in unsupNode.children)
                {
                    GenerateNodeStylesRecursive(child, sb, generatedClasses, document, false, currentLayoutMode, packageName);
                }
            }
        }

        public static string SanitizeClassName(string name, string id)
        {
            if (string.IsNullOrEmpty(name))
            {
                name = "element";
            }

            string sanitized = Regex.Replace(name.ToLowerInvariant(), @"[^a-z0-9_-]", "-");
            sanitized = Regex.Replace(sanitized, @"^-+", "");
            sanitized = Regex.Replace(sanitized, @"-+$", "");

            if (string.IsNullOrEmpty(sanitized) || char.IsDigit(sanitized[0]))
            {
                sanitized = "elem-" + sanitized;
            }

            string sanitizedId = Regex.Replace(id ?? "", @"[^a-zA-Z0-9_-]", "_");
            return $"{sanitized}-{sanitizedId}";
        }
    }
}
