using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Figma2Unity.Editor.Schema;

namespace Figma2Unity.Editor.Generator
{
    public static class USSStyleGenerator
    {
        public static string GenerateUSS(IRDocument document, string packageName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("/* Automatically generated by Figma2Unity Importer */");
            sb.AppendLine();

            var generatedClasses = new HashSet<string>();

            foreach (var rootNode in document.rootNodes)
            {
                GenerateNodeStylesRecursive(rootNode, sb, generatedClasses);
            }

            return sb.ToString();
        }

        public static string SanitizeClassName(string name, string id)
        {
            if (string.IsNullOrEmpty(name))
            {
                name = "element";
            }

            string sanitized = Regex.Replace(name.ToLowerInvariant(), @"[^a-z0-9_-]", "-");
            sanitized = Regex.Replace(sanitized, @"^-+", "");
            sanitized = Regex.Replace(sanitized, @"-+$", "");

            if (string.IsNullOrEmpty(sanitized) || char.IsDigit(sanitized[0]))
            {
                sanitized = "elem-" + sanitized;
            }

            string sanitizedId = Regex.Replace(id ?? "", @"[^a-zA-Z0-9_-]", "_");
            return $"{sanitized}-{sanitizedId}";
        }

        private static void GenerateNodeStylesRecursive(IRNode node, StringBuilder sb, HashSet<string> generatedClasses)
        {
            if (node == null) return;

            string className = SanitizeClassName(node.name, node.id);
            if (!generatedClasses.Contains(className))
            {
                generatedClasses.Add(className);
                sb.AppendLine($".{className} {{");

                GenerateFlexboxStyles(node, sb);
                GenerateVisualStyles(node, sb);

                sb.AppendLine("}");
                sb.AppendLine();
            }

            if (node is FrameNode frameNode && frameNode.children != null)
            {
                foreach (var child in frameNode.children)
                {
                    GenerateNodeStylesRecursive(child, sb, generatedClasses);
                }
            }
            else if (node is GroupNode groupNode && groupNode.children != null)
            {
                foreach (var child in groupNode.children)
                {
                    GenerateNodeStylesRecursive(child, sb, generatedClasses);
                }
            }
            else if (node is ComponentInstanceNode compNode && compNode.children != null)
            {
                foreach (var child in compNode.children)
                {
                    GenerateNodeStylesRecursive(child, sb, generatedClasses);
                }
            }
            else if (node is UnsupportedNode unsupNode && unsupNode.children != null)
            {
                foreach (var child in unsupNode.children)
                {
                    GenerateNodeStylesRecursive(child, sb, generatedClasses);
                }
            }
        }

        private static void GenerateFlexboxStyles(IRNode node, StringBuilder sb)
        {
            if (node.autoLayout != null && node.autoLayout.layoutMode != "NONE")
            {
                if (node.autoLayout.layoutMode == "HORIZONTAL")
                {
                    sb.AppendLine("    flex-direction: row;");
                }
                else if (node.autoLayout.layoutMode == "VERTICAL")
                {
                    sb.AppendLine("    flex-direction: column;");
                }

                // Justify Content (Primary Axis)
                switch (node.autoLayout.primaryAxisAlign)
                {
                    case "MIN":
                        sb.AppendLine("    justify-content: flex-start;");
                        break;
                    case "CENTER":
                        sb.AppendLine("    justify-content: center;");
                        break;
                    case "MAX":
                        sb.AppendLine("    justify-content: flex-end;");
                        break;
                    case "SPACE_BETWEEN":
                        sb.AppendLine("    justify-content: space-between;");
                        break;
                }

                // Align Items (Counter Axis)
                switch (node.autoLayout.counterAxisAlign)
                {
                    case "MIN":
                    case "BASELINE":
                        sb.AppendLine("    align-items: flex-start;");
                        break;
                    case "CENTER":
                        sb.AppendLine("    align-items: center;");
                        break;
                    case "MAX":
                        sb.AppendLine("    align-items: flex-end;");
                        break;
                }

                // Gap
                if (node.autoLayout.gap > 0)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    gap: {0}px;", node.autoLayout.gap));
                }

                // Padding
                if (node.autoLayout.padding != null)
                {
                    var p = node.autoLayout.padding;
                    if (p.top > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    padding-top: {0}px;", p.top));
                    if (p.right > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    padding-right: {0}px;", p.right));
                    if (p.bottom > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    padding-bottom: {0}px;", p.bottom));
                    if (p.left > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    padding-left: {0}px;", p.left));
                }

                // Layout Grow & Align Self
                if (node.autoLayout.layoutGrow > 0)
                {
                    sb.AppendLine("    flex-grow: 1;");
                    sb.AppendLine("    flex-shrink: 1;");
                }

                if (node.autoLayout.layoutAlign == "STRETCH")
                {
                    sb.AppendLine("    align-self: stretch;");
                }
            }
            else
            {
                // Absolute Positioning Layout Fallback
                if (node.bounds != null)
                {
                    if (node.bounds.width > 0)
                    {
                        sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    width: {0}px;", node.bounds.width));
                    }
                    if (node.bounds.height > 0)
                    {
                        sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    height: {0}px;", node.bounds.height));
                    }
                }
            }

            // Fixed bounds override when explicitly set
            if (node.autoLayout != null && node.autoLayout.primaryAxisSizingMode == "FIXED" && node.bounds != null)
            {
                if (node.autoLayout.layoutMode == "HORIZONTAL" && node.bounds.width > 0)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    width: {0}px;", node.bounds.width));
                    sb.AppendLine("    flex-shrink: 0;");
                }
                else if (node.autoLayout.layoutMode == "VERTICAL" && node.bounds.height > 0)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    height: {0}px;", node.bounds.height));
                    sb.AppendLine("    flex-shrink: 0;");
                }
            }
        }

        private static void GenerateVisualStyles(IRNode node, StringBuilder sb)
        {
            // Fills (Solid Background Color)
            if (node.fills != null && node.fills.Count > 0)
            {
                foreach (var fill in node.fills)
                {
                    if (fill.type == "SOLID" && fill.color != null)
                    {
                        float alpha = fill.opacity.HasValue ? fill.opacity.Value : fill.color.a;
                        int r = ConvertColorChannel(fill.color.r);
                        int g = ConvertColorChannel(fill.color.g);
                        int b = ConvertColorChannel(fill.color.b);
                        sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    background-color: rgba({0}, {1}, {2}, {3:F2});", r, g, b, alpha));
                        break;
                    }
                }
            }

            // Corner Radius
            if (node.cornerRadius != null)
            {
                var r = node.cornerRadius;
                if (r.topLeft > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-top-left-radius: {0}px;", r.topLeft));
                if (r.topRight > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-top-right-radius: {0}px;", r.topRight));
                if (r.bottomRight > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-bottom-right-radius: {0}px;", r.bottomRight));
                if (r.bottomLeft > 0) sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-bottom-left-radius: {0}px;", r.bottomLeft));
            }

            // Stroke (Border)
            if (node.strokes != null && node.strokes.Count > 0)
            {
                var stroke = node.strokes[0];
                if (stroke.weight > 0)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-width: {0}px;", stroke.weight));
                    if (stroke.color != null)
                    {
                        int r = ConvertColorChannel(stroke.color.r);
                        int g = ConvertColorChannel(stroke.color.g);
                        int b = ConvertColorChannel(stroke.color.b);
                        sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    border-color: rgba({0}, {1}, {2}, {3:F2});", r, g, b, stroke.color.a));
                    }
                }
            }

            // Opacity
            if (node.opacity < 1.0f)
            {
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    opacity: {0:F2};", node.opacity));
            }

            // Typography Styles for Text Nodes
            if (node is TextNode textNode)
            {
                if (textNode.fontSize.HasValue && textNode.fontSize.Value > 0)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "    font-size: {0}px;", textNode.fontSize.Value));
                }

                if (!string.IsNullOrEmpty(textNode.textAlign))
                {
                    switch (textNode.textAlign)
                    {
                        case "LEFT":
                            sb.AppendLine("    -unity-text-align: middle-left;");
                            break;
                        case "CENTER":
                            sb.AppendLine("    -unity-text-align: middle-center;");
                            break;
                        case "RIGHT":
                            sb.AppendLine("    -unity-text-align: middle-right;");
                            break;
                    }
                }
            }
        }

        private static int ConvertColorChannel(float value)
        {
            return (int)Math.Round(Math.Max(0f, Math.Min(1f, value)) * 255f);
        }
    }
}
